services:
  - type: web
    name: neonumy-album
    env: python
    buildCommand: pip install poetry && poetry install
    startCommand: >
      poetry run python manage.py migrate &&
      poetry run python manage.py collectstatic --noinput &&
      poetry run gunicorn neonumy_album.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: neonumy-album-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: neonumy-album-db
    databaseName: neonumy_album
    plan: free 